apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-mongo
  name: spring-boot-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-mongo
    spec:
      containers:
        - image: ykhadilkar/spring-boot-mongo
          name: spring-boot-mongo
          resources: {}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: spring-boot-mongo